sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t stocksoftware/chef-server .

script:
  - docker run -it --rm stocksoftware/chef-server sh -c 'chef-server-ctl help' ; if [ $? -eq 1 ]; then exit 0; else exit 1; fi
  - docker run -it --rm stocksoftware/chef-server sh -c 'chef-server-ctl cleanup' ; if [ $? -eq 1 ]; then exit 0; else exit 1; fi
